runtime: nodejs10

instance_class: F2

env_variables:
  DB_HOST: 35.237.41.117
  DB_PORT: 80
  DB_NAME: invoice
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_MAX_CONNECTION: 10

handlers:
- url: /public/css
  static_dir: public/css

- url: /public/images
  static_dir: public/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto